-- ============================================================
-- SaaS Platform Migration 004: Push Integration
-- Stores push-thera integration data after successful pairing.
-- Safe, fully additive – no existing data is removed.
-- ============================================================

SET NAMES utf8mb4;

-- Transient integration tokens (short-lived, 15min TTL)
CREATE TABLE IF NOT EXISTS `push_integration_tokens` (
  `id`          INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `token_hash`  VARCHAR(64)   NOT NULL COMMENT 'SHA-256 of the bearer token',
  `admin_id`    INT UNSIGNED  NOT NULL,
  `admin_email` VARCHAR(255)  NOT NULL,
  `admin_role`  VARCHAR(50)   NOT NULL,
  `expires_at`  DATETIME      NOT NULL,
  `created_at`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token_hash` (`token_hash`),
  KEY `idx_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `push_integration` (
  `id`                  INT UNSIGNED    NOT NULL AUTO_INCREMENT,
  `push_server_url`     VARCHAR(500)    NOT NULL,
  `client_id`           VARCHAR(100)    NOT NULL,
  `webhook_secret_hash` VARCHAR(255)    NOT NULL COMMENT 'SHA-256 hash of webhook secret',
  `internal_secret`     VARCHAR(255)    NOT NULL COMMENT 'Shared internal secret (hashed)',
  `vapid_public_key`    TEXT            NULL     COMMENT 'VAPID public key generated by push-thera',
  `integration_status`  ENUM('connected','error','disconnected') NOT NULL DEFAULT 'connected',
  `connected_at`        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_synced_at`      DATETIME        NULL,
  `notes`               TEXT            NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
